//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderDetail
    {
        public int OrderDetailID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quanlity { get; set; }
        public Nullable<double> PriceProduct { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> MoneyDiscount { get; set; }
        public Nullable<double> TotalMoney { get; set; }
    }
}
