//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> PriceProduct { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> GroupProductID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Quanlity { get; set; }
    }
}
