//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public Nullable<long> EmployeePhonenumber { get; set; }
        public Nullable<int> GroupEmployeeID { get; set; }
        public string AccountEmployee { get; set; }
        public string C_Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
    }
}
