//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Receipt
    {
        public int ReceiptID { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
