//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Manager
    {
        public int ManagerID { get; set; }
        public string ManagerName { get; set; }
        public string AccountManager { get; set; }
        public string C_Password { get; set; }
    }
}
