//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCVWithSotre.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        public int OrderID { get; set; }
        public string OrderCode { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> TotalProduct { get; set; }
        public Nullable<double> TotalMoney { get; set; }
        public Nullable<double> MoneyDiscount { get; set; }
        public Nullable<double> DiscountMoneyDirectly { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
